In [2]:
import torch
print(torch.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

2.1.0+cu121


In [3]:
#  scalar
scalar = torch.tensor(7) 
print(scalar)

tensor(7)


In [4]:
print(scalar.ndim)
print(scalar.shape)

0
torch.Size([])


In [5]:
print(scalar.item())

7


In [6]:
# Vector
vector = torch.tensor([1, 1])
vector

tensor([1, 1])

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix[0]

tensor([7, 8])

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9], 
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

<!-- @format -->

### random tensors


In [14]:
# create a random
random_tensor = torch.rand(10, 10, 10)
random_tensor

tensor([[[0.4192, 0.6505, 0.8707, 0.7762, 0.4384, 0.7625, 0.7584, 0.2986,
          0.4444, 0.5725],
         [0.1939, 0.0687, 0.3900, 0.1717, 0.9909, 0.6002, 0.5573, 0.2611,
          0.7636, 0.2843],
         [0.1098, 0.8175, 0.3171, 0.2965, 0.1633, 0.6913, 0.6010, 0.6905,
          0.2867, 0.4322],
         [0.1162, 0.4072, 0.3670, 0.3914, 0.2031, 0.9484, 0.9979, 0.4773,
          0.6628, 0.9078],
         [0.3184, 0.9212, 0.1854, 0.6223, 0.8760, 0.8543, 0.2196, 0.0240,
          0.1472, 0.4860],
         [0.6208, 0.7380, 0.9827, 0.5752, 0.8668, 0.2052, 0.7634, 0.2882,
          0.7803, 0.6282],
         [0.3792, 0.5716, 0.4608, 0.2687, 0.7936, 0.0730, 0.1628, 0.4226,
          0.5467, 0.0778],
         [0.0502, 0.3965, 0.6332, 0.3830, 0.8988, 0.1366, 0.7428, 0.0530,
          0.4816, 0.6932],
         [0.3206, 0.6868, 0.0236, 0.1952, 0.0546, 0.5023, 0.1755, 0.6230,
          0.4826, 0.7845],
         [0.7827, 0.4183, 0.2908, 0.8124, 0.8294, 0.5796, 0.6264, 0.5769,
          0.4187,

In [15]:
random_tensor.ndim

3

In [16]:
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

<!-- @format -->

### Zeros and Ones


In [17]:
# Create a tensor with all zeros
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
random_tensor = torch.rand(3, 4)
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

<!-- @format -->

### Creating a range of tensors and tensors-like


In [20]:
# Use torch.range
torch.arange(start=0, end=1000, step=67)

tensor([  0,  67, 134, 201, 268, 335, 402, 469, 536, 603, 670, 737, 804, 871,
        938])

In [21]:
one_to_ten = torch.arange(1, 11)
print(one_to_ten)
torch.zeros_like(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

<!-- @format -->

### Tensor Datatype


In [22]:
# Float 32 Dtype
float32_tensor = torch.tensor([3., 6., 9.], dtype=None, device=None, requires_grad=False)
float32_tensor

tensor([3., 6., 9.])

In [23]:
float32_tensor.dtype

torch.float32

In [24]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float16_tensor * float32_tensor

tensor([ 9., 36., 81.])

In [26]:
int32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int32_tensor

tensor([3, 6, 9])

In [27]:
int32_tensor * float32_tensor

tensor([ 9., 36., 81.])

<!-- @format -->

### Getting info from tensors


In [28]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4972, 0.3517, 0.1032, 0.6565],
        [0.4961, 0.3789, 0.2876, 0.0404],
        [0.3050, 0.9981, 0.4039, 0.1146]])

In [29]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4972, 0.3517, 0.1032, 0.6565],
        [0.4961, 0.3789, 0.2876, 0.0404],
        [0.3050, 0.9981, 0.4039, 0.1146]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


<!-- @format -->

### Manipulating Tensors (Tensor Operation)


In [30]:
tmp = torch.rand(3, 4)
tmp + 100

tensor([[100.1735, 100.0924, 100.5006, 100.6214],
        [100.8861, 100.7019, 100.3885, 100.1297],
        [100.1472, 100.6554, 100.5544, 100.6615]])

In [31]:
tmp * 100

tensor([[17.3501,  9.2374, 50.0569, 62.1448],
        [88.6135, 70.1943, 38.8481, 12.9746],
        [14.7211, 65.5361, 55.4349, 66.1511]])

In [32]:
tmp - 0.5

tensor([[-0.3265, -0.4076,  0.0006,  0.1214],
        [ 0.3861,  0.2019, -0.1115, -0.3703],
        [-0.3528,  0.1554,  0.0543,  0.1615]])

<!-- @format -->

### Matrix Multiplication


In [33]:
torch.matmul(torch.rand(3, 4), torch.rand(4, 3))

tensor([[0.9792, 0.9518, 0.9018],
        [1.0608, 1.1845, 1.0606],
        [0.9719, 1.1861, 1.2153]])

In [34]:
tensorA = torch.rand(3, 4)
tensorB = torch.rand(3, 4)
torch.matmul(tensorA.T, tensorB)

tensor([[0.5062, 0.1766, 0.2769, 0.5376],
        [0.8030, 0.2542, 0.5733, 0.9254],
        [0.9472, 0.2851, 0.6976, 1.1233],
        [1.0086, 0.3167, 0.7114, 1.1656]])

<!-- @format -->

### Min & Max & Sum & Mean & etc.


In [35]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [37]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [38]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [39]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

<!-- @format -->

### Find positional Min and Max


In [40]:
x, x.argmin(), x.argmax()

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), tensor(0), tensor(9))

<!-- @format -->

### Reshaping, Stacking, Squeezing and unsqueezing tensors


In [41]:
import torch
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [42]:
x_reshaped = x.reshape(3, 3)
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [43]:
z = x.view(3, 3)
z, z.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [44]:
z[:, 0] = 5
z, x

(tensor([[5, 2, 3],
         [5, 5, 6],
         [5, 8, 9]]),
 tensor([5, 2, 3, 5, 5, 6, 5, 8, 9]))

In [45]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [5, 5, 5, 5],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [46]:
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9]])

In [47]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5, 2, 3, 5, 5, 6, 5, 8, 9]), torch.Size([9]))

In [48]:
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed

tensor([[5],
        [2],
        [3],
        [5],
        [5],
        [6],
        [5],
        [8],
        [9]])

In [49]:
x = torch.rand(224, 224, 3)
x.size()

torch.Size([224, 224, 3])

In [50]:
torch.permute(x, (2, 0, 1)).shape

torch.Size([3, 224, 224])

<!-- @format -->

### Indexing


In [51]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [52]:
# index
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [53]:
x[0][0]

tensor([1, 2, 3])

In [54]:
x[:, 0, 0]

tensor([1])

In [55]:
import torch
import numpy as np
arr = np.arange(1., 10.)
tensor = torch.from_numpy(arr).type(torch.float32)
arr, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [56]:
arr = arr + 1
arr, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [57]:
# Tensor to Numpy
tensor = torch.ones(8)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [58]:
tensor = tensor * 2
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

<!-- @format -->

### Reproducbility


In [59]:
import torch
randA = torch.rand(3, 4)
randB = torch.rand(3, 4)
randA, randB, randA == randB

(tensor([[0.2152, 0.7937, 0.5576, 0.7206],
         [0.1614, 0.2229, 0.4402, 0.7524],
         [0.8354, 0.8753, 0.6936, 0.0296]]),
 tensor([[0.5208, 0.5620, 0.1147, 0.9473],
         [0.4103, 0.0565, 0.2727, 0.7350],
         [0.3802, 0.7110, 0.7033, 0.2123]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [60]:
# Random and reproducible tensors
import torch
RANDOM_SEED = 114514
torch.manual_seed(RANDOM_SEED)
randA = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
randB = torch.rand(3, 4)
randA == randB

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

<!-- @format -->

### Running tensors on GPUs


In [61]:
import torch
torch.cuda.is_available()

True

In [62]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [63]:
torch.cuda.device_count()

1

<!-- @format -->

### Put tensors on GPU


In [64]:
tensor = torch.tensor([1., 2., 3.])
tensorOnGPU = tensor.to(device)
tensorOnGPU

tensor([1., 2., 3.], device='cuda:0')

In [65]:
# move back to cpu
tensorOnCPU = tensorOnGPU.to("cpu")
tensorOnCPU.numpy()

array([1., 2., 3.], dtype=float32)