In [161]:
import torch
print(torch.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

2.1.0+cu121


In [162]:
#  scalar
scalar = torch.tensor(7) 
print(scalar)

tensor(7)


In [163]:
print(scalar.ndim)

0


In [164]:
print(scalar.item())

7


In [165]:
# Vector
vector = torch.tensor([1, 1])
vector

tensor([1, 1])

In [166]:
vector.shape

torch.Size([2])

In [167]:
# MATRIX
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [168]:
matrix[0]

tensor([7, 8])

In [169]:
matrix.shape

torch.Size([2, 2])

In [170]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9], 
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [171]:
TENSOR.ndim

3

In [172]:
TENSOR.shape

torch.Size([1, 3, 3])

### random tensors

In [173]:
# create a random
random_tensor = torch.rand(10, 10, 10)
random_tensor

tensor([[[0.7337, 0.8426, 0.5254, 0.1192, 0.8150, 0.5552, 0.0720, 0.7763,
          0.5997, 0.6236],
         [0.8828, 0.8254, 0.4195, 0.6911, 0.8054, 0.8969, 0.1099, 0.9399,
          0.9385, 0.7910],
         [0.6519, 0.6518, 0.1597, 0.6348, 0.4363, 0.7792, 0.7729, 0.4161,
          0.9873, 0.1084],
         [0.5691, 0.9368, 0.1649, 0.8992, 0.9081, 0.8996, 0.9207, 0.2480,
          0.1793, 0.2811],
         [0.9064, 0.4318, 0.9815, 0.2991, 0.7877, 0.9814, 0.8058, 0.9976,
          0.3800, 0.0816],
         [0.0333, 0.7730, 0.6748, 0.4286, 0.3036, 0.8547, 0.1621, 0.3596,
          0.5364, 0.9696],
         [0.7023, 0.3492, 0.7771, 0.0157, 0.5758, 0.4005, 0.5876, 0.6350,
          0.5283, 0.9492],
         [0.3370, 0.5341, 0.3019, 0.0194, 0.7261, 0.3013, 0.2594, 0.9451,
          0.4381, 0.6971],
         [0.3675, 0.9445, 0.0367, 0.8776, 0.7020, 0.0628, 0.5718, 0.8584,
          0.6010, 0.3850],
         [0.5323, 0.7977, 0.1858, 0.7535, 0.1235, 0.7423, 0.7884, 0.4810,
          0.5729,

In [174]:
random_tensor.ndim

3

In [175]:
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [176]:
# Create a tensor with all zeros
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [177]:
random_tensor = torch.rand(3, 4)
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [178]:
# Create tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [179]:
# Use torch.range
torch.arange(start=0, end=1000, step=67)

tensor([  0,  67, 134, 201, 268, 335, 402, 469, 536, 603, 670, 737, 804, 871,
        938])

In [180]:
one_to_ten = torch.arange(1, 11)
print(one_to_ten)
torch.zeros_like(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatype

In [181]:
# Float 32 Dtype
float32_tensor = torch.tensor([3., 6., 9.], dtype=None, device=None, requires_grad=False)
float32_tensor

tensor([3., 6., 9.])

In [182]:
float32_tensor.dtype

torch.float32

In [183]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [184]:
float16_tensor * float32_tensor

tensor([ 9., 36., 81.])

In [185]:
int32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int32_tensor

tensor([3, 6, 9])

In [186]:
int32_tensor * float32_tensor

tensor([ 9., 36., 81.])

### Getting info from tensors

In [187]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0475, 0.6507, 0.9329, 0.7599],
        [0.3590, 0.3804, 0.3120, 0.5603],
        [0.3794, 0.2651, 0.3538, 0.7687]])

In [188]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0475, 0.6507, 0.9329, 0.7599],
        [0.3590, 0.3804, 0.3120, 0.5603],
        [0.3794, 0.2651, 0.3538, 0.7687]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor Operation)

In [189]:
tmp = torch.rand(3, 4)
tmp + 100

tensor([[100.1308, 100.8909, 100.5518, 100.4296],
        [100.3610, 100.6626, 100.1595, 100.5512],
        [100.4217, 100.0053, 100.2962, 100.2059]])

In [190]:
tmp * 100

tensor([[13.0830, 89.0941, 55.1780, 42.9642],
        [36.0964, 66.2569, 15.9514, 55.1237],
        [42.1668,  0.5324, 29.6154, 20.5855]])

In [191]:
tmp - 0.5

tensor([[-0.3692,  0.3909,  0.0518, -0.0704],
        [-0.1390,  0.1626, -0.3405,  0.0512],
        [-0.0783, -0.4947, -0.2038, -0.2941]])

### Matrix Multiplication

In [192]:
torch.matmul(torch.rand(3, 4), torch.rand(4, 3))

tensor([[0.8243, 1.6586, 1.3864],
        [0.3404, 1.0412, 1.0763],
        [1.0320, 1.5983, 1.2388]])

In [193]:
tensorA = torch.rand(3, 4)
tensorB = torch.rand(3, 4)
torch.matmul(tensorA.T, tensorB)

tensor([[0.6646, 0.7425, 0.7662, 1.0291],
        [0.5050, 0.8576, 0.5039, 1.0162],
        [0.7978, 0.7777, 0.9383, 1.1815],
        [0.8158, 0.8413, 0.9082, 1.3672]])

### Min & Max & Sum & Mean & etc.

In [194]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [195]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [196]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [197]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [198]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Find positional Min and Max

In [199]:
x, x.argmin(), x.argmax()

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), tensor(0), tensor(9))

### Reshaping, Stacking, Squeezing and unsqueezing tensors

In [200]:
import torch
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [201]:
x_reshaped = x.reshape(3, 3)
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [202]:
z = x.view(3, 3)
z, z.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [203]:
z[:, 0] = 5
z, x

(tensor([[5, 2, 3],
         [5, 5, 6],
         [5, 8, 9]]),
 tensor([5, 2, 3, 5, 5, 6, 5, 8, 9]))

In [204]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [5, 5, 5, 5],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [205]:
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[5, 2, 3, 5, 5, 6, 5, 8, 9]])

In [206]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5, 2, 3, 5, 5, 6, 5, 8, 9]), torch.Size([9]))

In [207]:
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed

tensor([[5],
        [2],
        [3],
        [5],
        [5],
        [6],
        [5],
        [8],
        [9]])

In [208]:
x = torch.rand(224, 224, 3)
x.size()

torch.Size([224, 224, 3])

In [209]:
torch.permute(x, (2, 0, 1)).shape

torch.Size([3, 224, 224])

### Indexing

In [210]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [211]:
# index
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [212]:
x[0][0]

tensor([1, 2, 3])

In [213]:
x[:, 0, 0]

tensor([1])

In [214]:
import torch
import numpy as np
arr = np.arange(1., 10.)
tensor = torch.from_numpy(arr).type(torch.float32)
arr, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [215]:
arr = arr + 1
arr, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [216]:
# Tensor to Numpy
tensor = torch.ones(8)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [217]:
tensor = tensor * 2
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility

In [218]:
import torch
randA = torch.rand(3, 4)
randB = torch.rand(3, 4)
randA, randB, randA == randB

(tensor([[0.4489, 0.2849, 0.6123, 0.2507],
         [0.4809, 0.3570, 0.7793, 0.4519],
         [0.1917, 0.6357, 0.3017, 0.5383]]),
 tensor([[0.2576, 0.3461, 0.6841, 0.3127],
         [0.3545, 0.1745, 0.9540, 0.3545],
         [0.8928, 0.4842, 0.9862, 0.5088]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [219]:
# Random and reproducible tensors
import torch
RANDOM_SEED = 114514
torch.manual_seed(RANDOM_SEED)
randA = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
randB = torch.rand(3, 4)
randA == randB

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running tensors on GPUs

In [220]:
import torch
torch.cuda.is_available()

True

In [221]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [222]:
torch.cuda.device_count()

1

### Put tensors on GPU

In [223]:
tensor = torch.tensor([1., 2., 3.])
tensorOnGPU = tensor.to(device)
tensorOnGPU

tensor([1., 2., 3.], device='cuda:0')

In [224]:
# move back to cpu
tensorOnCPU = tensorOnGPU.to("cpu")
tensorOnCPU.numpy()

array([1., 2., 3.], dtype=float32)